# Generated by Django 4.2.6 on 2023-10-16 06:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_questions_student_alter_questions_exam_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questions",
            old_name="question_eight",
            new_name="question_1",
        ),
        migrations.RenameField(
            model_name="questions",
            old_name="question_five",
            new_name="question_10",
        ),
        migrations.RenameField(
            model_name="questions",
            old_name="question_four",
            new_name="question_2",
        ),
        migrations.RenameField(
            model_name="questions",
            old_name="question_nine",
            new_name="question_3",
        ),
        migrations.RenameField(
            model_name="questions",
            old_name="question_one",
            new_name="question_4",
        ),
        migrations.RenameField(
            model_name="questions",
            old_name="question_seven",
            new_name="question_5",
        ),
        migrations.RenameField(
            model_name="questions",
            old_name="question_six",
            new_name="question_6",
        ),
        migrations.RenameField(
            model_name="questions",
            old_name="question_ten",
            new_name="question_7",
        ),
        migrations.RenameField(
            model_name="questions",
            old_name="question_three",
            new_name="question_8",
        ),
        migrations.RenameField(
            model_name="questions",
            old_name="question_two",
            new_name="question_9",
        ),
    ]
