# Generated by Django 4.2.6 on 2023-10-10 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projectaccount", "0002_account_email_account_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="phone",
        ),
    ]
