# Generated by Django 4.2.6 on 2023-10-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectaccount", "0003_remove_account_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
