# Generated by Django 4.2.6 on 2023-10-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectaccount", "0004_account_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.EmailField(
                blank=True, max_length=60, null=True, unique=True, verbose_name="email"
            ),
        ),
    ]
