# Generated by Django 4.2.6 on 2023-10-10 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projectaccount", "0006_account_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="subject",
        ),
    ]
