# Generated by Django 4.2.6 on 2023-10-10 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
        ("projectaccount", "0007_remove_account_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_name",
                to="store.subject",
            ),
        ),
    ]
