# Generated by Django 4.2.6 on 2023-10-10 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
        ("projectaccount", "0008_account_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_name",
                to="store.subject",
            ),
            preserve_default=False,
        ),
    ]
